- pints/__init__.py
- pints/_optimisers/_pso.py
- pints/_util.py
- test/test_pso.py
> Added methods to set PSO stopping criteria, including tests.

- pints/_error_measures.py
- pints/_optimisers/__init__.py
- test/test_pso.py
> Bugfix for error when using logpdf in optimisation

- examples/EXAMPLES.md
- examples/writing-a-logpdf.ipynb
- pints/_optimisers/__init__.py
- test/test_pso.py
> Added example of writing a LogPDF

- docs/source/error_measures.rst
- pints/__init__.py
- pints/_error_measures.py
- test/test_error_measures.py
> Added MeanSquaredError and tests for error measures. Closes #242.

- docs/source/error_measures.rst
- docs/source/log_likelihoods.rst
- docs/source/log_pdfs.rst
- pints/__init__.py
- pints/_error_measures.py
- pints/_log_likelihoods.py
- pints/_log_pdfs.py
- test/test_error_measures.py
- test/test_log_likelihoods.py
- test/test_log_posterior.py
For issue #231 
This is about combining the results of independent single output problems defined on the same parameter space
> Issue#231 multi trace scores

- pints/_optimisers/_cmaes.py
> Made CMAES produce consistent results if a fixed number has been passed to np.random.seed

- pints/_optimisers/__init__.py
- pints/_optimisers/_cmaes.py
- test/test_cmaes.py
Error was due to cmaes getting stuck but Pints ignoring this information. Have added code to let optimiser classes tell the controller to stop! #247
> ValueError raised by cmaes

- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/_mcmc/_differential_evolution.py
- test/test_adaptive_mcmc.py
See #257
Needed for e.g. PopulationMCMC #186
> Changed SingleChainMCMC interface to work with multiple samples per iteration

- docs/source/io.rst
- pints/io.py
- test/test_io.py
> Simple code for loading/saving chains/sample lists

- pints/noise.py
- test/test_noise.py
This is in reference to @ #169.
> Added tests for noise generators.

- pints/_evaluation.py
- test/test_evaluators.py
> Improved evaluator tests.

- studies/problem-statement.ipynb
See #359. Could everyone please have a look?
[link for viewing](https://github.com/pints-team/pints/blob/de613b10696baae195832fb7b7499a3c2e963795/studies/problem-statement.ipynb)
If you want to change the notation, let's discuss that below! If you want to correct things or add things, feel free to push new commits to this branch!
@ben18785 @sanmitraghosh @martinjrobins @chonlei
> Consistent notation, log-likelihood & error equations, partial derivatives

- pints/__init__.py
- pints/_core.py
- pints/toy/_fitzhugh_nagumo_model.py
- pints/toy/_goodwin_oscillator_model.py
- pints/toy/_hh_ik_model.py
- pints/toy/_logistic_model.py
- test/test_logistic_model.py
after my git hassles ... this branch should be clean now, just with changes to add the toy model interface
> Issue 363 redux3 - add toy model interface

- pints/plot.py
- test/test_plot.py
> Add tests for pints.plot

- docs/source/index.rst
- docs/source/noise_generators.rst
- pints/__init__.py
- pints/_log_likelihoods.py
- pints/noise.py
- test/test_noise.py
> Rewrote noise adders as generators.

- pints/_mcmc/__init__.py
- test/test_mcmc_sampling.py
> #391 add method to MCMCSampling to access underlying samplers

- pints/__init__.py
- pints/_core.py
- pints/_mcmc/__init__.py
- pints/_mcmc/_differential_evolution.py
- pints/_mcmc/_metropolis.py
- pints/_optimisers/__init__.py
- pints/_optimisers/_cmaes.py
- pints/_optimisers/_pso.py
- test/test_cmaes.py
- test/test_differential_evolution_mcmc.py
- test/test_metropolis_mcmc.py
- test/test_pso.py
> Issue 393 hyper parameter interface

- pints/_optimisers/_cmaes.py
- pints/_optimisers/_pso.py
- pints/_optimisers/_snes.py
- pints/_optimisers/_xnes.py
- test/test_cmaes.py
- test/test_optimisation.py
- test/test_pso.py
- test/test_snes.py
- test/test_xnes.py
> More tests for optimisers

- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/tests/test_adaptive_mcmc.py
- pints/tests/test_differential_evolution_mcmc.py
- pints/tests/test_mcmc_sampling.py
- pints/tests/test_metropolis_mcmc.py
- pints/tests/test_population_mcmc.py
> Get coverage for _mcmc up to 100%

- docs/source/mcmc_samplers/base_classes.rst
- examples/sampling-adaptive-covariance-mcmc.ipynb
- examples/sampling-student-t-sampling-error.ipynb
- examples/writing-a-prior.ipynb
- pints/__init__.py
- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/tests/test_mcmc_adaptive.py
- pints/tests/test_mcmc_sampling.py
- pints/tests/test_nested_sampling.py
- studies/Fitzhugh-Nagumo-Inference.ipynb
> Add initial_phase to MCMCSampler interface

- docs/source/toy/index.rst
- docs/source/toy/normal_logpdf.rst
- pints/tests/test_toy_normal_logpdf.py
- pints/toy/__init__.py
- pints/toy/_normal.py
- pints/toy/_twisted_gaussian_banana.py
> Added normal logpdf toy example.

- pints/_diagnostics.py
- pints/tests/test_diagnostics.py
- studies/Untitled.ipynb
- studies/diagnostics.ipynb
> Diagnostics tests now implemented

- pints/_log_likelihoods.py
Now log-likelihood docstrings condition on data (I think -- I don't know how to check that my LaTex is working). See #470
> docstrings log-likelihood changes

- pints/_mcmc/_differential_evolution.py
Can we merge this please? Really minor fix.
> Small fix to differential evolution

- docs/source/index.rst
- docs/source/log_likelihoods.rst
- docs/source/log_pdfs.rst
- pints/__init__.py
- pints/_log_likelihoods.py
- pints/_log_pdfs.py
- pints/tests/test_log_likelihoods.py
- pints/tests/test_log_posterior.py
> Removed LogLikelihood class.

- pints/_mcmc/__init__.py
- pints/tests/test_mcmc_sampling.py
> Renamed log_rate log_interval. 

- .travis.yml
- CONTRIBUTING.md
- README.md
- pints/noise.py
- pints/tests/test_noise.py
> Test on Python 2.7.6

- pints/_mcmc/_population.py
@ben18785 I added this note to PopulationMCMC, does it make sense?
> Added note to pop mcmc docstring.

- pints/_optimisers/__init__.py
- pints/tests/test_opt_optimisation.py
> #558 add set_log_interval method to optimiser base class

- pints/tests/test_toy_logistic_model.py
- pints/toy/_logistic_model.py
> #355 fix sensitivities for logistic model edge cases

- pints/__init__.py
Hi all,
Just noticed we didn't have a docstring for the `pints` module itself. I've added a short one (typicaly format is one-liner, followed by longer paragraphs with proper explanation).
Please check if you agree
> Added docstring for the Pints module itself.

- pints/_optimisers/__init__.py
Hi all, just realised the docs didn't really say what an ask-and-tell interface is, so have added something in for the optimisers. Can you have a quick look and see if the wording makes sense?
> Added note on ask-and-tell.

- pints/_optimisers/__init__.py
> Fixes to dimension checking in optimisation

- CITATION
- README.md
https://www.software.ac.uk/blog/2016-10-06-encouraging-citation-software-introducing-citation-files
> Added CITATION file

- pints/_core.py
- pints/_log_likelihoods.py
- pints/tests/test_log_likelihoods.py
> #604 fix numpy shape bug in KnownLogLikelihood

- pints/_mcmc/_dream.py
- pints/tests/test_mcmc_dream.py
> #610 implicitly convert arg to int in set_nCR() for dream mcmc

- pints/_core.py
> #613 add a note specifying implicit conversion only for hyper-parameters

- pints/plot.py
- pints/tests/test_plot.py
Fix plotting errors with single parameter problems.
Fix #534
Fix #535
> Plot with single parameter

- pints/_nested/__init__.py
- pints/_nested/_ellipsoid.py
- pints/_nested/_rejection.py
- pints/tests/test_nested_sampling.py
> Issue 617 set hyper params

- pints/plot.py
- pints/tests/test_plot.py
> Add heatmap for pairwise

- pints/__init__.py
> Changed VERSION to __version__. 

- .travis.yml
- CONTRIBUTING.md
- requirements-dev.txt
- requirements-docs.txt
- requirements.txt
- setup.py
> Removed unneeded pip requirements files. Closes #565. Closes #601.

- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/_mcmc/_differential_evolution.py
- pints/_mcmc/_dream.py
- pints/_mcmc/_emcee_hammer.py
- pints/_mcmc/_hamiltonian.py
- pints/_mcmc/_metropolis.py
- pints/_mcmc/_population.py
- pints/_nested/__init__.py
- pints/_nested/_ellipsoid.py
- pints/_nested/_rejection.py
- pints/_optimisers/__init__.py
- pints/_optimisers/_cmaes.py
- pints/_optimisers/_pso.py
- pints/_optimisers/_snes.py
- pints/_optimisers/_xnes.py
- pints/tests/test_mcmc_differential_evolution.py
- pints/tests/test_mcmc_hamiltonian.py
- pints/toy/_high_dimensional_normal.py
- pints/toy/_multimodal_normal.py
- pints/toy/_twisted_gaussian_banana.py
> Changed internal _dimension variables to _n_parameters.

- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/_mcmc/_differential_evolution.py
- pints/_mcmc/_dream.py
- pints/_mcmc/_emcee_hammer.py
- pints/_mcmc/_hamiltonian.py
- pints/_mcmc/_metropolis.py
- pints/_mcmc/_population.py
- pints/tests/test_mcmc_adaptive.py
- pints/tests/test_mcmc_differential_evolution.py
- pints/tests/test_mcmc_dream.py
- pints/tests/test_mcmc_emcee_hammer.py
- pints/tests/test_mcmc_hamiltonian.py
- pints/tests/test_mcmc_metropolis.py
- pints/tests/test_mcmc_population.py
> Added current_log_pdf() method and current_log_pdfs() method to mcmc samplers

- docs/source/log_likelihoods.rst
> #607 add AR1 and ARMA1 classes to docs

- examples/optimisation-multi-objective.ipynb
See #52 
View here: https://github.com/pints-team/pints/blob/d0022bac3abdcf13d5f9a7eafa7add10af8bb617/examples/optimisation-multi-objective.ipynb
> Added example of multi-objective optimisation.

- pints/noise.py
- pints/tests/test_noise.py
Small changes to fix coverage (and make exception tests more specific)
> Fixed tests for noise generators (after changes to master a while back)

- examples/toy-distribution-rosenbrock.ipynb
- pints/toy/_rosenbrock.py
Changed text in example notebook as the description of the pdf was previously wrong (the readthedocs was correct).
> Change text in example notebook

- pints/_log_priors.py
> i722 log priors tidy

- docs/source/log_priors.rst
- pints/__init__.py
- pints/_log_priors.py
- pints/tests/test_log_priors.py
#725 adds inverse gamma and log normal log priors.
Also reimplements Cauchy, and orders unit tests alphabetically.
> I725 more log priors

- docs/source/core_classes_and_methods.rst
- docs/source/optimisers/index.rst
- docs/source/toy/index.rst
- docs/source/toy/neals_funnel.rst
- docs/source/utilities.rst
- pints/__init__.py
- pints/io.py
- pints/noise.py
- pints/plot.py
- run-tests.py
> I668 doc cover rst

- .slow-books
- run-tests.py
> I757 slow notebooks

- README.md
Add some contact info (email address) to README, and link to the issues page.
> Contact section in README

- README.md
> README fix broken link

- README.md
> Updated email address in README.

- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/_mcmc/_metropolis.py
- pints/tests/test_mcmc_adaptive.py
- pints/tests/test_mcmc_metropolis.py
> Updated interface of MCMCSampler.replace().

- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/_mcmc/_metropolis.py
- pints/tests/test_mcmc_adaptive.py
- pints/tests/test_mcmc_metropolis.py
> Revert "Updated interface of MCMCSampler.replace()."

- pints/_mcmc/__init__.py
- pints/_mcmc/_adaptive_covariance.py
- pints/_mcmc/_metropolis.py
- pints/tests/test_mcmc_adaptive.py
- pints/tests/test_mcmc_metropolis.py
Last one broke master somehow, investigating why
> MCMC.replace() method update, redux

- pints/_optimisers/__init__.py
- pints/_optimisers/_cmaes.py
- pints/tests/test_opt_cmaes.py
- pints/tests/test_opt_optimisation_controller.py
> Removed test that no longer triggers error condution with newer cma module

- pints/_nested/_ellipsoid.py
- pints/_nested/_rejection.py
> Fixing use of scipy logsumexp in nested samplers

- .appveyor.yml
- .travis.yml
- README.md
> Updating minimum Python 3 version to 3.5

- .appveyor.yml
- .travis.yml
> Adding testing for Python 3.7

- .travis.yml
Might be good keeping this in for a while, think it's possible! 
#546
> Attempting test 2.7.6 with different ubuntu distro

- pints/_optimisers/_cmaes.py
> Added the a new link for CMA-ES

- run-tests.py
> Made run_unit_tests() exit with correct return code.

- pints/_mcmc/_slice_stepout.py
- pints/tests/test_slice_stepout.py
Integrate "overrelaxation" into "_slice_stepout.py" and modify tests file.
> Slice sampling overrelaxation

- CITATION
> Update CITATION file

- .flake8
- CONTRIBUTING.md
- pints/_log_likelihoods.py
- pints/_mcmc/_differential_evolution.py
- pints/_mcmc/_slice_doubling.py
- pints/_mcmc/_slice_stepout.py
- pints/tests/test_opt_cmaes.py
- pints/tests/test_opt_nelder_mead.py
- pints/tests/test_opt_pso.py
- pints/tests/test_opt_snes.py
- pints/tests/test_opt_xnes.py
- pints/tests/test_plot.py
- pints/toy/_annulus.py
- pints/toy/_constant_model.py
- pints/toy/_fitzhugh_nagumo_model.py
- pints/toy/_logistic_model.py
- run-tests.py
because latex docstrings should be in raw strings.
See #735
> Let flake8 check for invalid escape sequences again

- README.md
> Added link to Ben's visualisation to README

- pints/tests/test_mcmc_hamiltonian.py
- pints/tests/test_mcmc_mala.py
- pints/tests/test_toy_gaussian_logpdf.py
- pints/toy/_gaussian.py
> Value-based tests for toy gaussian problem

- pints/_mcmc/_hamiltonian.py
> Correction to HMC docstrings

- .slow-books
- examples/sampling-hamiltonian-mcmc.ipynb
- examples/sampling-monomial-gamma-hmc.ipynb
See #926 
Removed unwanted code from notebooks. Added monomial gamma hmc to list of slow untested notebooks.
> Fixes for notebook testing

- pints/_log_priors.py
- pints/tests/test_log_priors.py
- fixed sampling for half Cauchy
- added value based tests for various
> Added value based tests for log priors

- pints/_mcmc/_hamiltonian.py
- pints/_mcmc/_monomial_gamma_hamiltonian.py
- pints/tests/test_mcmc_hamiltonian.py
- pints/tests/test_mcmc_monomial_gamma_hmc.py
> Divergent iterations setter for HMC and Monomial gamma

- pints/_mcmc/_hamiltonian.py
- pints/_mcmc/_monomial_gamma_hamiltonian.py
> HMC and MG docstring correction

- pints/tests/test_opt_easy_optimisation.py
- pints/tests/test_toy_br_ap_model.py
- pints/tests/test_toy_constant_model.py
- pints/tests/test_toy_fitzhugh_nagumo_model.py
- pints/tests/test_toy_goodwin_oscillator_model.py
- pints/tests/test_toy_hes1_michaelis_menten_model.py
- pints/tests/test_toy_hh_ik_model.py
- pints/tests/test_toy_logistic_model.py
- pints/tests/test_toy_lotka_volterra_model.py
- pints/tests/test_toy_repressilator.py
- pints/tests/test_toy_sir_model.py
- pints/toy/_beeler_reuter_model.py
- pints/toy/_goodwin_oscillator_model.py
- pints/toy/_hh_ik_model.py
- pints/toy/_sir_model.py
> Value-based tests of toy models

- CITATION
- README.md
- papers/README.md
- papers/main-pints.bib
- papers/used-pints.bib
See #914 
Proposed structure:
```
papers/
- README.md
- main-pints.bib
- used-pints.bib
```
> Papers using PINTS

- pints/_mcmc/_slice_doubling.py
- pints/_mcmc/_slice_stepout.py
- pints/tests/test_mcmc_slice_doubling.py
- pints/tests/test_mcmc_slice_stepout.py
Fixes issue #992 
And a few small tweaks
> 992 slice tests

- pints/toy/_logistic_model.py
> #1003 fix error in dydk

- LICENSE.txt
Makes github recognise it and display info.
> Added license name to LICENSE.txt.

- pints/_nested/__init__.py
> Allowing logsumexp import from alternative location in scipy.

- pints/_mcmc/__init__.py
- pints/tests/test_mcmc_controller.py
Made MCMCController tests more granular (similar to open issue #980)
In the process saw that one of the tests was wrong, fixed it, and uncovered bug (then fixed that)
> More granular MCMCController test structure, and bugfix

- examples/sampling-adaptive-covariance-haario-bardenet.ipynb
- examples/sampling-adaptive-covariance-haario.ipynb
> Fixed broken links in notebooks

- CONTRIBUTING.md
> Added tiny note about language to contributing.md

- pints/_log_priors.py
> 1042 use logpdf for multivariate normal prior

- pints/tests/test_toy_fitzhugh_nagumo_model.py
- pints/tests/test_toy_goodwin_oscillator_model.py
- pints/tests/test_toy_lotka_volterra_model.py
- pints/toy/_fitzhugh_nagumo_model.py
- pints/toy/_toy_classes.py
> Fixed bug with ToyModelODE when t=0 wasn't included in requested time points

- pints/toy/_lotka_volterra_model.py
Had an extra `_simulate()` which is no longer needed
> Removed unneeded method from Lotka-Volterra model.

- pints/_mcmc/_metropolis.py
> Metropolis MCMC docstrings pseudocode

- docs/source/index.rst
Closes #817. Nothing but one letter typo...
> Fix EmceeHammerMCMC typo in docs

- examples/README.md
- examples/optimisation/ask-and-tell.ipynb
- examples/optimisation/transformed-parameters.ipynb
They weren't easy to find (both were recently missed by people who know pints reasonably well), and were written as optimisation-specific, while they're actually more generally applicable than that.
Have tried to remedy
> Updated ask-and-tell and transformed-parameters examples.

- pints/toy/_logistic_model.py
> Update docs for logistic model

- examples/optimisation/cmaes.ipynb
- examples/optimisation/pso.ipynb
- examples/optimisation/snes.ipynb
- examples/optimisation/transformed-parameters.ipynb
- examples/optimisation/xnes.ipynb
> Updated examples to use plt instead of pl

- examples/stats/autoregressive-moving-average-errors.ipynb
I made some changes to the text in the AR and ARMA notebook for issue #1102 .
> 1102 arma notebook intro

- .flake8
- pints/toy/_toy_classes.py
@ben18785 and @MichaelClerx I've added what I wanted to for issue #1120, and pre-commit checks have all passed. All I've done is add a few comments and change the thing I spotted.
> commenting ToyODEModel class

- pints/_error_measures.py
No issue for this one, just a suggested improvement!
> Clarified weights in error measure docstrings.

- pints/_optimisers/_pso.py
With this fix you can store the points that were passed back from ask(), and they won't later be modified
> Fixed PSO issue where points returned by ask were later modified.

- .github/workflows/unit-test-os-coverage.yml
- .github/workflows/unit-test-python-coverage.yml
> Tweaked names of unit test actions.

- docs/source/boundaries.rst
- docs/source/core_classes_and_methods.rst
- docs/source/diagnostics.rst
- docs/source/error_measures.rst
- docs/source/function_evaluation.rst
- docs/source/log_likelihoods.rst
- docs/source/log_pdfs.rst
- docs/source/log_priors.rst
- docs/source/noise_generators.rst
- docs/source/utilities.rst
- pints/_diagnostics.py
- pints/_error_measures.py
- pints/_log_likelihoods.py
- pints/_log_priors.py
- pints/noise.py
See #1114.
A table of contents exists now on every subpage in the dos, as well as a more detailed list in the side bar. Here and there the docstrings were improved by teXing the fomulas.
> I1114 table of content subpage

- pints/tests/test_mcmc_controller.py
- pints/tests/test_nested_sampling.py
- pints/tests/test_opt_optimisation_controller.py
- pints/tests/test_opt_pso.py
Investigating some issues with multiprocessing: the issues I'm seeing may not be PINTS related, but did notice these tests could be more stringent
> Better tests for parallelisation.

- pints/__init__.py
> Testing to see if something has changed with coverage of __init__

- pints/_log_likelihoods.py
- pints/tests/test_log_likelihoods.py
Closes #1179 .
I fixed the issue reported in the issue above and changed the docstring accordingly.
> I1179 Improve multiplicative gaussian loglikelihood code and docs

- pints/_diagnostics.py
- pints/_log_likelihoods.py
- pints/_log_priors.py
- pints/_mcmc/__init__.py
- pints/_mcmc/_differential_evolution.py
- pints/_mcmc/_haario_bardenet_ac.py
- pints/_mcmc/_summary.py
- pints/_optimisers/__init__.py
- pints/_optimisers/_cmaes.py
- pints/_optimisers/_cmaes_bare.py
- pints/_optimisers/_nelder_mead.py
- pints/_optimisers/_pso.py
- pints/_optimisers/_snes.py
- pints/_optimisers/_xnes.py
- pints/tests/test_opt_cmaes.py
- pints/tests/test_opt_cmaes_bare.py
- pints/tests/test_opt_gradient_descent.py
- pints/tests/test_opt_nelder_mead.py
> Replaced calls to logging.Logger.warning() with warnings.warn().

- CONTRIBUTING.md
- README.md
- Users can now install with pip, without cloning the repo
- Virtualenv and conda get a mention in the contributing docs
- Added some guidelines for release. This is just my opinion on things, so please comment/modify/discuss/lament/etc!
> README and CONTRIBUTING updates for new pip install

- pints/tests/test_opt_optimisation_controller.py
> Broken test on OS/X

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
See #1202 
Anyone have any opinions on this?
Feel free to adapt/expand the current draft for whatever-comes-after-0.3.0 !
Would like to get this merged asap so that currently open PRs can start adding to it as well
> Added a CHANGELOG.md file

- CHANGELOG.md
Closes #1221 . Is this sufficient @chonlei ?
> I1221 fix changelog pooled log pdf

- CHANGELOG.md
- pints/_mcmc/_population.py
@ben18785 could you have a look at this too?
- pop mcmc gave very odd distributions, and accepted very unlikely points (#1238)
- discovered two bugs, both in way exchange was handled
- fixed now, but performance still awful, because the base chain can suddenly jump to very unlikely points from the other chains. This _always_ gives a distribution that is far too wide, and the effect gets stronger with more iterations
Am I missing something?
> Fixing population MCMC

- .github/workflows/copyright-test.yml
- .github/workflows/coverage-test.yml
- .github/workflows/docs-test.yml
- .github/workflows/notebook-test.yml
- .github/workflows/style-test.yml
- .github/workflows/unit-test-os-coverage.yml
- .github/workflows/unit-test-python-coverage.yml
- .github/workflows/upload-to-pypi.yml
Hi @ben18785 ! This should make it easier for us to see which tests are which
> Ensure all github actions have nice job names

- CHANGELOG.md
> Includes missing changelogs

- CHANGELOG.md
- pints/_mcmc/_nuts.py
- pints/tests/test_mcmc_nuts.py
> Added divergence detection for NUTS in the build_tree function

- pints/_mcmc/_differential_evolution.py
> Removes while loop from DE code

- pints/tests/shared.py
- pints/tests/test_interfaces_stan.py
See #1305 
Makes the unit test output readable again.
~Although possibly harder to debug now if things go wrong.~
Have now made it so that it prints all if an error occurs
> Capturing pystan test output

- pints/tests/test_toy_high_dimensional_gaussian_logpdf.py
- pints/toy/_gaussian.py
- pints/toy/_high_dimensional_gaussian.py
- Made docstrings for high dim Gaussian more informative
- Cached covariance matrix for Gaussian case
- Added reference for derivative of log density for Gaussian
Addresses #1328
> Added evaluateS1 for high dim Gaussian

- pints/_mcmc/_emcee_hammer.py
- pints/tests/test_mcmc_emcee_hammer.py
- Separated sample_z out into its own function as this makes more explicit what's happening
- Cleaned up choosing a member from the complementary set
- Corrected the setter for scale (and corrected its test)
Addresses #1325
> Bug fix in emcee hammer

- pints/tests/test_toy_eight_schools_logpdf.py
- pints/toy/_eight_schools.py
- Returns negative infinity if sd proposed is negative
- Avoids us having to change the way that all log priors work
addresses #1267
> Eight schools negative standard deviation fix

- .github/workflows/notebook-interfaces-test.yml
> Fix to interfaces notebook workflow.

- pints/tests/test_log_likelihoods.py
> switch to assertAlmostEqual for likelihood testing

- example.svg
> Added white background to example.svg.

- README.md
Change the link to example.svg on master branch instead of a specific commit; Closes #1366
> Update link to image in README

- pints/tests/test_evaluators.py
- run-tests.py
- setup.py
> Seeing if test will hang again

- CHANGELOG.md
- docs/source/mcmc_samplers/running.rst
- docs/source/utilities.rst
Includes missing changelog for #1322 
Also moved documentation to utilities folder.
> Include changelog for sampling and optimisation initialisation PR

- CHANGELOG.md
- pints/_optimisers/__init__.py
- pints/tests/test_opt_optimisation_controller.py
> Callback function in optimisation controller.

- setup.py
> Set maintainer info in setup.py to use mailing list.

- CHANGELOG.md
Fixes #1419 
updates changelog for version 0.4.0 release. I'll tag a release once this is merged
> #1419 changelog update to 0.4.0

- LICENSE.md
- docs/source/conf.py
> Updated copyright notices to 2022.

- pints/plot/_pairwise.py
> Fix tiny docs typo

- setup.py
These will show up on pypi.
As it's not a change to PINTS itself I propose to leave this out of the changelog.
> Added URL meta data to setup.py

- CHANGELOG.md
- docs/source/transformations.rst
- pints/__init__.py
- pints/_transformation.py
- pints/tests/shared.py
- pints/tests/test_opt_controller.py
- pints/tests/test_transformation.py
> Added TransformedRectangularBoundaries class.

- .gitignore
- README.md
> #1477 update badge url

- CHANGELOG.md
- docs/source/log_likelihoods.rst
- pints/__init__.py
- pints/_log_likelihoods.py
- pints/plot/_pairwise.py
- pints/tests/test_log_likelihoods.py
> I1483 gaussian integrated log uniform log likelihood

- .readthedocs.yaml
- CONTRIBUTING.md
Addresses #1487 
~Not sure how to test~
> Added .readthedocs.yaml

- .github/workflows/copyright-test.yml
- .github/workflows/coverage-test.yml
- .github/workflows/docs-test.yml
- .github/workflows/style-test.yml
- .github/workflows/unit-test-os-coverage.yml
- .github/workflows/unit-test-python-coverage.yml
- CONTRIBUTING.md
- README.md
- docs/source/conf.py
- docs/source/index.rst
- examples/interfaces/stan.ipynb
- examples/stats/constant-and-multiplicative-gaussian-error.ipynb
Fixes #1486
Note: Also changed this for changepoint testing repo
> Renaming master to main

- docs/source/log_priors.rst
- pints/__init__.py
- pints/_log_priors.py
- pints/tests/test_log_priors.py
This PR adds a log uniform prior, as implemented in `scipy.stats`. Please let me know if there are any issues or anything, I went through `CONTRIBUTING.md` and think I got it all.
Fixes #1498
> LogUniformLogPrior

- CHANGELOG.md
Hi @ben18785 , @abillscmu ,
Just noticed that #1499 was missing an update to the changelog
@abillscmu Please correct or improve if necessary, but I think it's already OK :D 
@ben18785 Please can you do a review and merge once the tests have passed?
> Update CHANGELOG.md after 1499

- CHANGELOG.md
- README.md
- pints/_error_measures.py
- pints/_log_pdfs.py
See #682 
Could also go in definition of error and likelihood ~?~ !
> Add note to readme on discrete parameters

- LICENSE.md
> Updated copyright date in LICENSE.md
