pints/_log_pdfs.py, pints/_log_priors.py, requirements.txt, setup.py, test/test_log_priors.py
The LogPrior classes needed tests, and not all of them had the new `sample()` method.
See #200
=> Added sample() methods and tests to all LogPrior classes

pints/toy/_fitzhugh_nagumo_model.py, test/test_fitzhugh_nagumo_model.py
similar to previous logistic sensitivities, but for an ode model
=> add sensitivities for fitzhugh nagumo model

docs/source/core_classes_and_methods.rst, pints/__init__.py, pints/_core.py, pints/_error_measures.py, pints/_log_likelihoods.py, pints/_log_pdfs.py, pints/_log_priors.py, pints/toy/_constant_model.py, pints/toy/_fitzhugh_nagumo_model.py, pints/toy/_logistic_model.py, test/test_constant_model.py, test/test_error_measures.py, test/test_fitzhugh_nagumo_model.py, test/test_log_likelihoods.py, test/test_log_posterior.py, test/test_log_priors.py, test/test_logistic_model.py
This one stays much closer to (basically _is_) what @martinjrobins did before, and lets users use the same LogPDF, Problem, etc. for methods with and without sensitivities (provided the used objects all support them), like @ben18785 wanted. It also allows models to implement both the `ForwardModel` and the `ForwardModelS1` class, if they want.
I've also coded up a loglikelihood with sensitivities, which wasn't fun. It did make me think that maybe we should swap the order of the multi-dimensional array indices we're using.
At the moment it's `(n_times, n_outputs)` for a multioutput problem, so `y[10]` gives you both outputs at time 10.
For sensitivities, that then becomes `(n_times, n_outputs, n_parameters)`, so that `dy[10, 2]` gives you the derivatives w.r.t p at time 10, for output 2. …
=> i43 sensitivities: A third proposal

pints/_optimisers/__init__.py
Example:
```
Minimising error measure
using Covariance Matrix Adaptation Evolution Strategy (CMA-ES)
Running in parallel with 2 worker processes.
Population size: 10
Iter. Eval. Best      Time m:s
0     10     1.426383   0:36.3
^C
----------------------------------------
Unexpected termination.
Current best score: 1.42638335249
Current best position:
-5.03125667726224624e+00
3.06015611698052734e-02
-2.66105137709121520e+00
4.97419923893682517e-02
-1.06324505952824815e+01
8.48175421713438446e-03
-1.94280811004977494e+00
1.14010059985587588e-02
5.69589430131492769e-01
----------------------------------------
Traceback (most recent call last):
File "./simulation-fit.py", line 347, in <module>
parallel=2,
File "/home/michael/dev/pints/pints/_optimisers/__init__.py", line 885, in fmin
return …
```
=> Made optimisation show the final result if an exception occurs or the user cancels.

pints/_mcmc/_dream.py
See #472 
@ben18785, can you have a look at the changes (just hit the "files changed" button on this PR) and tell me if you think this is ok? I'm guessing it's fine (if a little arbitrary), as `p` would have been `inf` for at least 1 iteration before...
=> Avoided div-by-zero in dream

pints/_mcmc/__init__.py
and MCMCSampling.samplers()
See #488
=> Improved documentation and error message for MCMCSampling.sampler()

requirements-dev.txt, run-tests.py
Made sure they're only imported when notebook tests are being run, so that non-dev users can run tests without having to install them.
Closes #544
=> Added traitlets and nbconvert to dev dependencies. 

pints/tests/test_mcmc_sampling.py, pints/tests/test_opt_optimisation.py
=> Stopped comparing time strings in optimisation and mcmc sampling logging tests.

pints/_log_likelihoods.py, pints/tests/test_error_measures.py, pints/tests/test_log_likelihoods.py, pints/tests/test_toy_constant_model.py, pints/toy/_constant_model.py
In this checking of the tests, I (somewhat disconcertingly) found about a dozen errors that would have been picked up if we were doing value-based tests of log-likelihoods. The errors were on the following:
- AR1 values for multiple output problems
- ARMA11 values for multiple output problems
- Gaussian log likelihood values and derivatives for multiple output problems. Given that this is our workhorse distribution for many problems this was particularly concerning
- The ConstantModel which we use for testing previously had incorrect derivatives; these should always be 1 since f = theta -> df / dtheta = 1.
Covers #719
=> Value-based tests for log-likelihoods

pints/_error_measures.py, pints/_optimisers/__init__.py, pints/_optimisers/_cmaes.py, pints/_optimisers/_pso.py, pints/_optimisers/_snes.py, pints/_optimisers/_xnes.py, pints/tests/test_error_measures.py, pints/tests/test_opt_optimisation_controller.py, pints/tests/test_opt_pso.py
It seems the way we were doing irregular boundaries in CMA-ES, using `nan` to tell cma-es points couldn't be evaluated, makes it much less robust than simply returning `inf`.
=> Irregular boundary handling in CMA-ES

pints/tests/test_toy_twisted_gaussian_logpdf.py, pints/toy/_twisted_gaussian_banana.py
Also added value-based test (before I made the changes) to test they don't affect the result
See #784
=> Cosmetic changes to twisted gaussian

pints/_optimisers/__init__.py, pints/tests/test_opt_optimisation_controller.py
See #861 
Currently have `iterations()`, `evaluations()`, and `time()`. 
Could consider adding more e.g. `fbest()`, `xbest()` (or similar)
Could also consider adding similar methods to MCMCController and others (but in a separate PR, ideally)
=> Add "results object" methods to OptimisationController

pints/tests/test_log_likelihoods.py, pints/toy/_fitzhugh_nagumo_model.py
@ben18785 could you have a look at this? I spotted a bug:
self.assertTrue(np.abs(y - ll(x) < 1e-6))
this asserts that np.abs(z) is true, where z is the expression `y - ll(x) < 1e-6`
As it turns out, `y - ll(x)` is negative, so that z = True, and abs(z) = 1...
Corrected the bracket mistake, but now the tolerance is no longer met
=> Bug in loglikelihoods test.

pints/_log_priors.py, pints/tests/test_log_priors.py
Addresses #978 and hopefully #973
=> Multivariate Gaussian sensitivities

pints/_mcmc/_differential_evolution.py
We're not explicit about this in the docs, but MCMC methods have two options for ask():
1. Only allow one call (we do this for hamiltonian methods) between tells
2. Return the same proposal if ask() is called repeatedly
DiffEv followed pattern number 2, but updated an iteration count with each call
=> Repeated calls to DiffEv ask() increased iteration count.

pints/_mcmc/__init__.py, pints/tests/test_mcmc_controller.py
=> 584 dont store chains

CONTRIBUTING.md
Added some links to the explanation of why docstrings start with a single-line paragraph
=> Updated contributing.md with one- and multi-line docstring guidelines

.github/workflows/copyright-test.yml, .github/workflows/coverage-test.yml, .github/workflows/docs-test.yml, .github/workflows/notebook-test.yml, .github/workflows/style-test.yml, .github/workflows/unit-test-os-coverage.yml, .github/workflows/unit-test-python-coverage.yml, .github/workflows/unit-tests.yml
See #1074 and #848 
This PR adds GitHub actions scripts for:
- copyright
- coverage
- doctest
- style
- unit tests (Python 3.8 on [ubuntu-16.04, macos-latest, windows-latest])
- unit tests (ubuntu-18.04 on Python [2.7, 3.5, 3.6, 3.7, 3.8])
These are set to run on pushes to the current branch and master, and all pull requests.
In addition there is a GitHub actions script for:
- notebooks
which is set to run on a cron job at 1am every Friday morning.
I would suggest merging these changes now.  They are all additions so will run as well as Travis, AppVeyor etc.  Once it's merged and working on master, we can tidy up the existing integrations, change over the status badges, etc.
=> i1074 gh actions

pints/_log_likelihoods.py
Here's my current work on Small Issue #676. When this is finished, I think it should close #694 and #734 as well.
@ben18785  let me know if I've managed to get this correct and understandable. One of the main issues with these models seems to be the question of whether to work out the exact likelihood or condition on some initial observations for simplicity. In Pints it looks like the conditional likelihoods have been implemented, so I included that in the docstring. 
For both AR(1) and ARMA(1,1), we are currently using a transformed variance parameter for the white noise (e.g., sigma' = sigma sqrt{1-rho^2} for AR(1)). Is there a good justification or reference for these rescalings that you think we should mention in the docstring?
=> 676 ar arma docs

pints/_optimisers/__init__.py, pints/tests/test_opt_easy_optimisation.py
Closes #761.
Convenience method `curve_fit` now returns the final error function evaluation too, which makes it consistent with all other optimisation methods.
On the other hand, the user didn't actually define this error, so might not care about the value. So I'm happy to drop this PR too :D
=> Made 'curve_fit' return the best parameters and final error function value

pints/plot/_surface.py, pints/tests/test_boundaries.py, pints/tests/test_plot.py, pints/tests/test_residuals_diagnostics.py
Here is a edit which appears to fix #1184 .
Having `_voronoi_regions` return a 1d numpy object array doesn't work with the latest matplotlib PolyCollection code. I think this should fix the broken unit test and notebook since matplotlib-3.3.0.
=> Fix matplotlib bug in surface

pints/_log_priors.py, pints/tests/test_log_priors.py
=> HalfCauchy.sample returns (n,1) array

pints/tests/test_opt_optimisation_controller.py
Made optimisation controller logging test robust against varying execution times.
Fixes #1205 
Follows up from #1206
=> Randomly failing os/x test, part 2

examples/stats/beginners-tutorial.ipynb, pints/_transformation.py
Closes #1217.
Apparently when subclasses inherit methods, those references in the parent class method will be considered as duplicated references. So I have moved those references to the class's docstrings (instead of methods' docstrings).
=> Fix docstring warning

.github/workflows/unit-test-python-coverage.yml, LICENSE.md
=> Testing Python3.9 testing

pints/_transformation.py, pints/tests/test_transformation.py
=> Fix small typo in transformation docs

docs/source/diagnostics.rst, pints/_diagnostics.py
=> Documentation (and naming?) changes in pints.diagnostics

examples/sampling/effective-sample-size.ipynb, pints/_diagnostics.py, pints/tests/test_diagnostics.py
=> Documentation (and naming?) changes in pints.diagnostics: redux

pints/_mcmc/_differential_evolution.py, pints/tests/test_mcmc_controller.py, pints/tests/test_mcmc_differential_evolution.py
- Addresses #1291 
- Tidies up DifferentialEvolution: alphabeticises and also added getters for hyperparameters which were before only private variables (I came across this because I was using DE for the multi-chain tests to address the main issue)
=> Tests that hyperparameters remain constant before / after MCMC run

.github/workflows/copyright-test.yml, .github/workflows/coverage-test.yml, .github/workflows/docs-test.yml, .github/workflows/style-test.yml, .github/workflows/unit-test-os-coverage.yml, .github/workflows/unit-test-python-coverage.yml
Hi both!
I think I've worked out the full syntax to do this?
- The first line is new, and updates the list of "events" on a PR that trigger checks
https://docs.github.com/en/enterprise-server@3.0/actions/reference/events-that-trigger-workflows
It adds "ready_to_review" to the 3 default events, which means that going from draft to normal PR now triggers checks
- The second line is the one Ben added, & which Fergus correctly moved to the job. (I don't understand why, it looks more natural in the above bit to me, but that doesn't work!)
**Update** forgot to create the first PR as draft to show that this works
=> Skip draft PRs, but run when a draft is marked as ready for review (part 3)

pints/toy/_neals_funnel.py
The derivative of Neal's Funnel is now returned(in the evaluateS1 function) as a numpy array which makes it usable with NUTS.
=> Fixed Neal's Funnel Derivative bug

pints/_evaluation.py, pints/tests/shared.py
Hi @martinjrobins !
I did a bit of testing and it looks like these capture methods should be OK when used in multiprocessing: https://github.com/MichaelClerx/myokit/issues/727
I've checked with `spawn` and `fork`, so should handle the windows & linux defaults
So I've downgradedd the warning to "not thread safe" (which I think is the issue you were having)
This is good news w.r.t. myokit as well, as it's much easier to make it thread-safe than it would be to fix similar issues for multiprocessing!
=> Subcapture warning pt 2

docs/source/conf.py
- Removed use of [`autodoc_default_flags`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_flags), because:
- It was deprecated in 1.8, sphinx is now onto 4.x
- The check to see which version to use assumed we were still on 1.x
- Changed copyright year from 2019 to 2021
=> Updated sphinx conf.py

CHANGELOG.md, pints/_evaluation.py
Made `pints.evaluate()` limit the number of workers to the number of jobs, to avoid having unneeded workers.
Note we can't do this in `ParallelEvaluator`, where the number of jobs is unknown and variable
=> Made pints.evaluate() limit the number of workers to the number of jobs.

.github/workflows/copyright-test.yml, .github/workflows/coverage-test.yml, .github/workflows/docs-test.yml, .github/workflows/style-test.yml, .github/workflows/unit-test-os-coverage.yml, .github/workflows/upload-to-pypi.yml
=> Updated workflows to skip Ubuntu 16, and use Python 3.9 where possible.

CHANGELOG.md, pints/_evaluation.py, pints/tests/test_evaluators.py
See #1358
Tasks are evaluated by "workers". Each worker starts with a copy of the main process's random generator. So unless we do some seeding they will all use the same random numbers!
Works like this:
```
main process wants to evaluate f(x) on 100 points x
generates a list of 100 tuples (index, seed, x)
each worker waits for a task, and when it gets one it:
- seeds its private random generator using "seed"
- evaluates f(x)
- passes back a tuple (index, f(x))
main process receives all the (index, f(x)) pairs, 
stores them at results[index] = f(x)
```
By seeding in this way it doesn't matter which worker evaluates f(x), or in which order the tasks are evaluated - the results are always reproducible
(And of course if we don't seed the main process, then they are reproducible but …
=> Seed worker threads for different, but reproducible, results

pints/_mcmc/_mala.py
The equation for `alpha` seems to have a typo in which `\theta^*` was present in the nominator and denominator. The correct version should be with `\theta_t` in the denominator, see https://en.wikipedia.org/wiki/Metropolis-adjusted_Langevin_algorithm.
=> Fix alpha equation for MALAMCMC

CHANGELOG.md, pints/_evaluation.py, pints/tests/test_evaluators.py, setup.py
See #1356 
Current solution allows customisation of `ParallelEvaluator` class, but doesn't provide options for the `pints.evaluate` method or for controllers (which just use the new default)
=> Restrict numpy multithreading when multiprocessing

pints/residuals_diagnostics.py, run-tests.py
- Added `residuals_diagnostics` to doc coverage tests
- This showed that 3 external modules were exposed as part of `pints.residuals_diagnostics`, so changed the place where they were imported.
=> Added residuals_diagnostics to doc coverage tests

pints/plot/_histogram.py, pints/plot/_trace.py
When chains run across different areas, since they use separate bin sizes across the chains, the resultant histograms can be incomparable. This PR picks a consistent bin size across them.
addresses #1389
=> Standardise histogram bins across chains

pints/cptests/__init__.py, pints/cptests/_discovery.py, pints/cptests/_problems.py, pints/cptests/differential_evolution_mcmc.py, pints/cptests/dram_acmc.py, pints/cptests/dream_mcmc.py, pints/cptests/emcee_hammer_mcmc.py, pints/cptests/haario_acmc.py, pints/cptests/haario_bardenet_acmc.py, pints/cptests/hamiltonian_mcmc.py, pints/cptests/mala_mcmc.py, pints/cptests/metropolis_random_walk_mcmc.py, pints/cptests/monomial_gamma_hamiltonian_mcmc.py, pints/cptests/no_u_turn_mcmc.py, pints/cptests/population_mcmc.py, pints/cptests/relativistic_mcmc.py, pints/cptests/slice_stepout_mcmc.py
=> Renamed function to change point tests.

CHANGELOG.md, docs/source/optimisers/boundary_transformations.rst, docs/source/optimisers/index.rst, pints/__init__.py, pints/_optimisers/__init__.py, pints/_optimisers/_cmaes_bare.py, pints/_optimisers/_pso.py, pints/_optimisers/_snes.py, pints/_optimisers/_xnes.py, pints/tests/test_opt_optimisation_controller.py
See #25 (and #1420)
It leads to errors with xnes, where it just keeps increasing sigma because it keeps finding points in the next "period" of the search space. The `TriangleWaveTransform` is used by PSO, xNES, SNES, and BareCMAES. All of these methods can easily deal with "inf" for any evaluation, and this was already the way we handled arbitrary shaped boundaries.
In addition, found and fixed a bug in PSO where we (I) initialised with too many particles
=> Stop using triangle wave transform in optimisations

.github/workflows/copyright-test.yml, .github/workflows/coverage-test.yml, .github/workflows/docs-test.yml, .github/workflows/notebook-interfaces-test.yml, .github/workflows/notebook-test.yml, .github/workflows/style-test.yml, .github/workflows/unit-test-os-coverage.yml, .github/workflows/unit-test-python-coverage.yml, .github/workflows/upload-to-pypi.yml, CHANGELOG.md
@fcooper8472 @martinjrobins what do you think of the 2nd change? Is this a good idea in your opinion (the whole `with` block can be removed in that case, x64 is default too), or are we better off explicitly specifying the newest version we want to test on?
=> Test on Python 3.10

CHANGELOG.md, pints/_transformation.py
=> Gave ScalingTransformation private properties and added equation to docstring

CHANGELOG.md, examples/optimisation/gradient-descent.ipynb, pints/_optimisers/_gradient_descent.py, pints/tests/test_opt_gradient_descent.py
Updated its tests to ignore boundaries. Updated its docstring to make clear that it does this.
=> Made gradient descent set its learning rate as min(sigma0)

pints/_error_measures.py
Moved `ninv` out of sum (it's a scalar).
Reduced excessive bracketing
Now more consistent with equation in evaluateS1
=> Simplified notation in MeanSquaredError.__call__.

.github/workflows/copyright-test.yml, .github/workflows/coverage-test.yml, .github/workflows/docs-test.yml, .github/workflows/notebook-interfaces-test.yml, .github/workflows/notebook-test.yml, .github/workflows/style-test.yml, .github/workflows/unit-test-os-coverage.yml, .github/workflows/unit-test-python-coverage.yml, .github/workflows/upload-to-pypi.yml
Currently fails due to pystan and nuts asyncio #1473
- Updated to actions/checkout@v3 and actions/setup-python@v4
- Temporarily restricted testing to at most 3.10
=> Temporarily stop tests running on Python 3.11

.github/workflows/unit-test-os-coverage.yml, CHANGELOG.md
- Ubuntu 18 is no longer supported https://ubuntu.com/18-04
- We specify testing on 18.04 and "latest", which used to mean 18+20, but now means 18+22
- Tests no longer run on 18
- This PR drops 18.04 testing, and adds 20.04 testing
=> Updated testing from Ubuntu 18+22 to 20+22.

CHANGELOG.md, pints/_error_measures.py, pints/_log_likelihoods.py, pints/_log_priors.py, pints/_mcmc/__init__.py, pints/_optimisers/__init__.py, pints/tests/test_log_priors.py
=> #1496 replace np.product by np.prod everywhere

CHANGELOG.md, examples/optimisation/snes.ipynb, pints/_abc/__init__.py, pints/_mcmc/__init__.py, pints/_nested/__init__.py, pints/_optimisers/__init__.py, pints/tests/test_abc_controller.py, pints/tests/test_mcmc_adaptive.py, pints/tests/test_mcmc_controller.py, pints/tests/test_nested_controller.py, pints/tests/test_opt_adam.py, pints/tests/test_opt_controller.py, pints/tests/test_opt_irpropmin.py, pints/tests/test_opt_nelder_mead.py, pints/tests/test_opt_pso.py
=> Removed units from time headers in controllers.

README.md
Seems tests are failing somehow, so creating PR to check it out
=> Tests are failing?

pints/tests/test_opt_gradient_descent.py
Should have done this in the first place 🙈
=> Added value-based test for gradient descent.

.github/workflows/copyright-test.yml, .github/workflows/coverage-test.yml, .github/workflows/docs-test.yml, .github/workflows/notebook-interfaces-test.yml, .github/workflows/notebook-test.yml, .github/workflows/style-test.yml, .github/workflows/unit-test-os-coverage.yml, .github/workflows/unit-test-python-coverage.yml, .github/workflows/upload-to-pypi.yml
Updates `checkout` to v4 and `setup-python` to v5 to fix this warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
And sets a python version in the style test to fix this warning:
> The `python-version` input is not set. The version of Python currently in `PATH` will be used.
=> Updated github actions versions.

CHANGELOG.md, docs/source/boundaries.rst, pints/__init__.py, pints/_boundaries.py, pints/tests/shared.py, pints/tests/test_boundaries.py, pints/tests/test_test_shared.py
Lets you create a boundaries object from other boundaries objects.
The naming and syntax is the same as ComposedLogPrior and ComposedTransformation
This has a use case in our ion channel issues, where we often have 2d boundaries on a pair of parameters, and then a total set of boundaries made up of multiples of these 2d ones
=> Adds a ComposedBoundaries, similar to ComposedLogPrior.

pints/_optimisers/_nelder_mead.py, pints/tests/test_mcmc_relativistic.py
1. Not many changes in PINTS luckily, just replacing a `np.array(x, copy=False)` with `np.asarray(x)`
2. Remaining errors are in `pycma`. These are already fixed in development but we'll need to wait for a new release.
=> Updates for numpy 2 compatibility

pints/_mcmc/_haario_bardenet_ac.py
doi.org was missing in the link to a source
=> Update link to source in Haario Bardenet ACMC

pints/_error_measures.py
Copied from MeanSquaredError docs
=> Added missing documentation for weights parameter in SumOfSquaresError

.github/workflows/notebook-interfaces-test.yml, .github/workflows/notebook-test.yml
- Interfaces notebooks require older python because stan doesn't support 3.13 yet
- Renewal-estimation notebook uses pandas, wasn't easy to replace so added pandas installation to notebook testing
=> Notebook tests fixes

.github/workflows/coverage-test.yml, .github/workflows/notebook-interfaces-test.yml, .github/workflows/unit-test-os-coverage.yml, .github/workflows/upload-to-pypi.yml
=> Updated ubuntu and some versions used in actions
